FROM node:16-alpine as builder

WORKDIR /app

ARG SCOPE

ENV PORT=3000
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51MXHdEFwhEz4kIqD7ZyQo6HcYhFY03byVW2SHpQOglZBDhTeZ0jkqknptPK63R2kc8BMRlXP534sw7femKMV05PE00SbVdp8jA
ENV NEXT_PUBLIC_APP_URL=https://booking.bitmetro.io
ENV NEXT_PUBLIC_API_URL=https://booking-api.bitmetro.io

COPY . .
RUN yarn global add turbo@1.5.5 && \
    turbo prune --scope=${SCOPE} && \
    cd out && \
    yarn install && \
    turbo run build --scope=${SCOPE} --include-dependencies && \
    rm -rf node_modules/.cache .yarn/cache

FROM node:16-alpine as app

WORKDIR /app
COPY --chown=node:node --from=builder /app/out .

ARG SCOPE

ENV NODE_ENV=production
ENV PORT=3000
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51MXHdEFwhEz4kIqD7ZyQo6HcYhFY03byVW2SHpQOglZBDhTeZ0jkqknptPK63R2kc8BMRlXP534sw7femKMV05PE00SbVdp8jA
ENV NEXT_PUBLIC_APP_URL=https://booking.bitmetro.io
ENV NEXT_PUBLIC_API_URL=https://booking-api.bitmetro.io

WORKDIR /app/apps/${SCOPE}

EXPOSE 3000
CMD yarn start